/******************************************************************************* 
 * PROJECT NAME : FOOTBALL PLAYER DATABASE                                    
 *                                                                            
 * UNIVERSITY   : FEDERICO II - NAPOLI - ITALY                                 
 * FIELD        : COMPUTER SCIENCE                                            
 * CLASS        : DATA BASES I                                                
 * TEACHER      : SILVIO BARRA                                                
 * YEAR         : 2023-2024                                                   
 ******************************************************************************/


/*******************************************************************************
 * INSERT COUNTRY
 ******************************************************************************/


/*******************************************************************************
 * INSERT WORLD TYPE COUNTRY
 ******************************************************************************/
INSERT INTO country (type, code, name)
VALUES
('WORLD', 'WLD', 'World');
--------------------------------------------------------------------------------


/*******************************************************************************
 * INSERT CONTINENT TYPE COUNTRY
 ******************************************************************************/
INSERT INTO country (type, code, name)
VALUES
('CONTINENT', 'AFR', 'Africa'),
('CONTINENT', 'ASI', 'Asia'),
('CONTINENT', 'ATA', 'Antartica'),
('CONTINENT', 'EUR', 'Europe'),
('CONTINENT', 'NCA', 'North Center America'),
('CONTINENT', 'OCN', 'Oceania'),
('CONTINENT', 'STA', 'South America');
--------------------------------------------------------------------------------


/*******************************************************************************
 * INSERT NATION TYPE COUNTRY
 ******************************************************************************/
INSERT INTO country (type, code, name)
VALUES
('NATION', 'AFG', 'Afghanistan'),
('NATION', 'AGO', 'Angola'),
('NATION', 'ALB', 'Albania'),
('NATION', 'AND', 'Andorra'),
('NATION', 'ARE', 'United Arab Emirates'),
('NATION', 'ARG', 'Argentina'),
('NATION', 'ARM', 'Armenia'),
('NATION', 'ATG', 'Antigua and Barbuda'),
('NATION', 'AUS', 'Australia'),
('NATION', 'AUT', 'Austria'),
('NATION', 'AZE', 'Azerbaijan'),
('NATION', 'BDI', 'Burundi'),
('NATION', 'BEL', 'Belgium'),
('NATION', 'BEN', 'Benin'),
('NATION', 'BFA', 'Burkina Faso'),
('NATION', 'BGD', 'Bangladesh'),
('NATION', 'BGR', 'Bulgaria'),
('NATION', 'BHR', 'Bahrain'),
('NATION', 'BHS', 'Bahamas'),
('NATION', 'BIH', 'Bosnia and Herzegovina'),
('NATION', 'BLR', 'Belarus'),
('NATION', 'BLZ', 'Belize'),
('NATION', 'BOL', 'Bolivia'),
('NATION', 'BRA', 'Brazil'),
('NATION', 'BRB', 'Barbados'),
('NATION', 'BRN', 'Brunei'),
('NATION', 'BTN', 'Bhutan'),
('NATION', 'BWA', 'Botswana'),
('NATION', 'CAF', 'Central African Republic'),
('NATION', 'CAN', 'Canada'),
('NATION', 'CHE', 'Switzerland'),
('NATION', 'CHL', 'Chile'),
('NATION', 'CHN', 'China'),
('NATION', 'CIV', 'Côte d''Ivoire'),
('NATION', 'CMR', 'Cameroon'),
('NATION', 'COD', 'Democratic Republic of the Congo'),
('NATION', 'COG', 'Congo'),
('NATION', 'COL', 'Colombia'),
('NATION', 'COM', 'Comoros'),
('NATION', 'CPV', 'Cabo Verde'),
('NATION', 'CRI', 'Costa Rica'),
('NATION', 'CUB', 'Cuba'),
('NATION', 'CUW', 'Curaçao'),
('NATION', 'CYP', 'Cyprus'),
('NATION', 'CZE', 'Czech Republic'),
('NATION', 'DEU', 'Germany'),
('NATION', 'DJI', 'Djibouti'),
('NATION', 'DMA', 'Dominica'),
('NATION', 'DNK', 'Denmark'),
('NATION', 'DOM', 'Dominican Republic'),
('NATION', 'DZA', 'Algeria'),
('NATION', 'ECU', 'Ecuador'),
('NATION', 'EGY', 'Egypt'),
('NATION', 'ENG', 'England'),
('NATION', 'ERI', 'Eritrea'),
('NATION', 'ESP', 'Spain'),
('NATION', 'EST', 'Estonia'),
('NATION', 'ETH', 'Ethiopia'),
('NATION', 'FIN', 'Finland'),
('NATION', 'FJI', 'Fiji'),
('NATION', 'FRA', 'France'),
('NATION', 'FSM', 'Micronesia'),
('NATION', 'GAB', 'Gabon'),
('NATION', 'GBR', 'United Kingdom'),
('NATION', 'GEO', 'Georgia'),
('NATION', 'GHA', 'Ghana'),
('NATION', 'GIN', 'Guinea'),
('NATION', 'GMB', 'Gambia'),
('NATION', 'GNB', 'Guinea-Bissau'),
('NATION', 'GNQ', 'Equatorial Guinea'),
('NATION', 'GRC', 'Greece'),
('NATION', 'GRD', 'Grenada'),
('NATION', 'GTM', 'Guatemala'),
('NATION', 'GUY', 'Guyana'),
('NATION', 'HND', 'Honduras'),
('NATION', 'HRV', 'Croatia'),
('NATION', 'HTI', 'Haiti'),
('NATION', 'HUN', 'Hungary'),
('NATION', 'IDN', 'Indonesia'),
('NATION', 'IND', 'India'),
('NATION', 'IRL', 'Ireland'),
('NATION', 'IRN', 'Iran'),
('NATION', 'IRQ', 'Iraq'),
('NATION', 'ISL', 'Iceland'),
('NATION', 'ISR', 'Israel'),
('NATION', 'ITA', 'Italy'),
('NATION', 'JAM', 'Jamaica'),
('NATION', 'JOR', 'Jordan'),
('NATION', 'JPN', 'Japan'),
('NATION', 'KAZ', 'Kazakhstan'),
('NATION', 'KEN', 'Kenya'),
('NATION', 'KGZ', 'Kyrgyzstan'),
('NATION', 'KHM', 'Cambodia'),
('NATION', 'KIR', 'Kiribati'),
('NATION', 'KNA', 'Saint Kitts and Nevis'),
('NATION', 'KOR', 'South Korea'),
('NATION', 'KWT', 'Kuwait'),
('NATION', 'LAO', 'Lao People''s Democratic Republic'),
('NATION', 'LBN', 'Lebanon'),
('NATION', 'LBR', 'Liberia'),
('NATION', 'LBY', 'Libya'),
('NATION', 'LCA', 'Saint Lucia'),
('NATION', 'LIE', 'Liechtenstein'),
('NATION', 'LKA', 'Sri Lanka'),
('NATION', 'LSO', 'Lesotho'),
('NATION', 'LTU', 'Lithuania'),
('NATION', 'LUX', 'Luxembourg'),
('NATION', 'LVA', 'Latvia'),
('NATION', 'MAR', 'Morocco'),
('NATION', 'MCO', 'Monaco'),
('NATION', 'MDA', 'Moldova'),
('NATION', 'MDG', 'Madagascar'),
('NATION', 'MDV', 'Maldives'),
('NATION', 'MEX', 'Mexico'),
('NATION', 'MHL', 'Marshall Islands'),
('NATION', 'MKD', 'North Macedonia'),
('NATION', 'MLI', 'Mali'),
('NATION', 'MLT', 'Malta'),
('NATION', 'MMR', 'Myanmar'),
('NATION', 'MNE', 'Montenegro'),
('NATION', 'MNG', 'Mongolia'),
('NATION', 'MOZ', 'Mozambique'),
('NATION', 'MRT', 'Mauritania'),
('NATION', 'MUS', 'Mauritius'),
('NATION', 'MWI', 'Malawi'),
('NATION', 'MYS', 'Malaysia'),
('NATION', 'NAM', 'Namibia'),
('NATION', 'NER', 'Niger'),
('NATION', 'NGA', 'Nigeria'),
('NATION', 'NIC', 'Nicaragua'),
('NATION', 'NIR', 'Northern Ireland'),
('NATION', 'NIU', 'Niue'),	
('NATION', 'NLD', 'Netherlands'),
('NATION', 'NOR', 'Norway'),
('NATION', 'NPL', 'Nepal'),
('NATION', 'NRU', 'Nauru'),
('NATION', 'NZL', 'New Zealand'),
('NATION', 'OMN', 'Oman'),
('NATION', 'PAK', 'Pakistan'),
('NATION', 'PAN', 'Panama'),
('NATION', 'PER', 'Peru'),
('NATION', 'PHL', 'Philippines'),
('NATION', 'PLW', 'Palau'),
('NATION', 'PNG', 'Papua New Guinea'),
('NATION', 'POL', 'Poland'),
('NATION', 'PRI', 'Puerto Rico'),
('NATION', 'PRK', 'North Korea'),
('NATION', 'PRT', 'Portugal'),
('NATION', 'PRY', 'Paraguay'),
('NATION', 'PSE', 'Palestine'),
('NATION', 'QAT', 'Qatar'),
('NATION', 'ROU', 'Romania'),
('NATION', 'RUS', 'Russian Federation'),
('NATION', 'RWA', 'Rwanda'),
('NATION', 'SAU', 'Saudi Arabia'),
('NATION', 'SCT', 'Scotland'),
('NATION', 'SDN', 'Sudan'),
('NATION', 'SEN', 'Senegal'),
('NATION', 'SGP', 'Singapore'),
('NATION', 'SLB', 'Solomon Islands'),
('NATION', 'SLE', 'Sierra Leone'),
('NATION', 'SLV', 'El Salvador'),
('NATION', 'SMR', 'San Marino'),
('NATION', 'SOM', 'Somalia'),
('NATION', 'SRB', 'Serbia'),
('NATION', 'SSD', 'South Sudan'),
('NATION', 'STP', 'São Tomé and Príncipe'),
('NATION', 'SUR', 'Suriname'),
('NATION', 'SVK', 'Slovakia'),
('NATION', 'SVN', 'Slovenia'),
('NATION', 'SWE', 'Sweden'),
('NATION', 'SWZ', 'Eswatini'),
('NATION', 'SYC', 'Seychelles'),
('NATION', 'SYR', 'Syria'),
('NATION', 'TCD', 'Chad'),
('NATION', 'TGO', 'Togo'),
('NATION', 'THA', 'Thailand'),
('NATION', 'TJK', 'Tajikistan'),
('NATION', 'TKM', 'Turkmenistan'),
('NATION', 'TLS', 'Timor-Leste'),
('NATION', 'TON', 'Tonga'),
('NATION', 'TTO', 'Trinidad and Tobago'),
('NATION', 'TUN', 'Tunisia'),
('NATION', 'TUR', 'Türkiye'),
('NATION', 'TWN', 'Taiwan'),
('NATION', 'TZA', 'Tanzania'),
('NATION', 'UGA', 'Uganda'),
('NATION', 'UKR', 'Ukraine'),
('NATION', 'URY', 'Uruguay'),
('NATION', 'USA', 'United States'),
('NATION', 'UZB', 'Uzbekistan'),
('NATION', 'VCT', 'Saint Vincent and the Grenadines'),
('NATION', 'VEN', 'Venezuela'),
('NATION', 'VNM', 'Vietnam'),
('NATION', 'VUT', 'Vanuatu'),
('NATION', 'WLS', 'Wales'),
('NATION', 'WSM', 'Samoa'),
('NATION', 'XKX', 'Kosovo'),
('NATION', 'YEM', 'Yemen'),
('NATION', 'YUG', 'Jugoslavia'),
('NATION', 'ZAF', 'South Africa'),
('NATION', 'ZMB', 'Zambia'),
('NATION', 'ZWE', 'Zimbabwe');
--------------------------------------------------------------------------------


