/******************************************************************************* 
 * PROJECT NAME : FOOTBALL PLAYER DATABASE                                    
 *                                                                            
 * UNIVERSITY   : FEDERICO II - NAPOLI - ITALY                                 
 * FIELD        : COMPUTER SCIENCE                                            
 * CLASS        : DATA BASES I                                                
 * TEACHER      : SILVIO BARRA                                                
 * YEAR         : 2023-2024                                                   
 ******************************************************************************/

 
/*******************************************************************************
 * INSERT CONFEDERATION
 ******************************************************************************/


/*******************************************************************************
 * INSERT WORLD TYPE CONFEDERATION
 ******************************************************************************/
INSERT INTO conf (type, code, name, year)
VALUES
('WORLD', 'FIFA', 'Fédération Internationale de Football Association', 1904);
--------------------------------------------------------------------------------

/*******************************************************************************
 * INSERT CONTINENT TYPE CONFEDERATION
 ******************************************************************************/
INSERT INTO conf (type, code, name, year)
VALUES
('CONTINENT', 'CAF', 'Confederation of African Football', 1957),
('CONTINENT', 'AFC', 'Asian Football Confederation', 1954),
('CONTINENT', 'CONCACAF', 'Confederation of North and Central America and Caribbean Association Football', 1961),
('CONTINENT', 'CONMEBOL', 'Confederación Sudamericana de Fútbol', 1916),
('CONTINENT', 'OFC', 'Oceania Football Confederation', 1966),
('CONTINENT', 'UEFA', 'Union of European Football Associations', 1954);
--------------------------------------------------------------------------------

/*******************************************************************************
 * INSERT NATION TYPE CONFEDERATION
 ******************************************************************************/
INSERT INTO conf (type, code, name, year)
VALUES
('NATION', 'AFF', 'Afghanistan Football Federation', 1922),
('NATION', 'FAF', 'Angolan Football Federation', 1979),
('NATION', 'FSHF', 'Federata Shqiptare e Futbollit', 1930),
('NATION', 'FAF', 'Federació Andorrana de Futbol', 1994),
('NATION', 'UAEFA', 'UAE Football Association', 1971),
('NATION', 'AFA', 'Asociación del Fútbol Argentino', 1893),
('NATION', 'FFA', 'Football Federation of Armenia', 1992),
('NATION', 'ABFA', 'Antigua and Barbuda Football Association', 1928),
('NATION', 'FFA', 'Football Federation Australia', 1961),
('NATION', 'ÖFB', 'Österreichischer Fußball-Bund', 1904),
('NATION', 'AFFA', 'Association of Football Federations of Azerbaijan', 1992),
('NATION', 'FFB', 'Fédération de Football du Burundi', 1948),
('NATION', 'KBVB', 'Royal Belgian Football Association', 1895),
('NATION', 'FBF', 'Fédération Béninoise de Football', 1962),
('NATION', 'FBF', 'Fédération Burkinabé de Football', 1960),
('NATION', 'BFF', 'Bangladesh Football Federation', 1972),
('NATION', 'BFU', 'Bulgarian Football Union', 1923),
('NATION', 'BFA', 'Bahrain Football Association', 1957),
('NATION', 'BFA', 'Bahamas Football Association', 1967),
('NATION', 'N/FSBiH', 'Nogometni/Fudbalski Savez Bosne i Hercegovine', 1992),
('NATION', 'BFF', 'Football Federation of Belarus', 1989),
('NATION', 'FFB', 'Football Federation of Belize', 1980),
('NATION', 'FBF', 'Federación Boliviana de Fútbol', 1925),
('NATION', 'CBF', 'Confederação Brasileira de Futebol', 1914),
('NATION', 'BFA', 'Barbados Football Association', 1910),
('NATION', 'NFABD', 'National Football Association of Brunei Darussalam', 1959),
('NATION', 'BFF', 'Bhutan Football Federation', 1983),
('NATION', 'BFA', 'Botswana Football Association', 1970),
('NATION', 'FCF', 'Fédération Centrafricaine de Football', 1961),
('NATION', 'CSA', 'Canada Soccer', 1912),
('NATION', 'SFV', 'Swiss Football Association', 1895),
('NATION', 'FFCh', 'Federación de Fútbol de Chile', 1895),
('NATION', 'CFA', 'Chinese Football Association', 1924),
('NATION', 'FIF', 'Fédération Ivoirienne de Football', 1960),
('NATION', 'FECAFOOT', 'Fédération Camerounaise de Football', 1959),
('NATION', 'FECOFA', 'Fédération Congolaise de Football-Association', 1919),
('NATION', 'FECOFOOT', 'Fédération Congolaise de Football', 1962),
('NATION', 'FCF', 'Federación Colombiana de Fútbol', 1924),
('NATION', 'FFC', 'Fédération Comorienne de Football', 1979),
('NATION', 'FCF', 'Federação Caboverdiana de Futebol', 1982),
('NATION', 'FEDEFUTBOL', 'Federación Costarricense de Fútbol', 1921),
('NATION', 'AFC', 'Asociación de Fútbol de Cuba', 1924),
('NATION', 'FFK', 'Federashon Futbòl Kòrsou', 2010),
('NATION', 'CFA', 'Cyprus Football Association', 1934),
('NATION', 'FAČR', 'Fotbalová asociace České republiky', 1901),
('NATION', 'DFB', 'Deutscher Fußball-Bund', 1900),
('NATION', 'FDF', 'Fédération Djiboutienne de Football', 1979),
('NATION', 'DFA', 'Dominica Football Association', 1970),
('NATION', 'DBU', 'Dansk Boldspil-Union', 1889),
('NATION', 'FEDOFUTBOL', 'Federación Dominicana de Fútbol', 1953),
('NATION', 'FAF', 'Fédération Algérienne de Football', 1962),
('NATION', 'FEF', 'Federación Ecuatoriana de Fútbol', 1925),
('NATION', 'EFA', 'Egyptian Football Association', 1921),
('NATION', 'ENFF', 'Eritrean National Football Federation', 1996),
('NATION', 'RFEF', 'Real Federación Española de Fútbol', 1909),
('NATION', 'EJL', 'Eesti Jalgpalli Liit', 1921),
('NATION', 'EFF', 'Ethiopian Football Federation', 1943),
('NATION', 'SPL', 'Suomen Palloliitto', 1907),
('NATION', 'FFA', 'Fiji Football Association', 1961),
('NATION', 'FFF', 'Fédération Française de Football', 1919),
('NATION', 'FSMFA', 'Federated States of Micronesia Football Association', 1996),
('NATION', 'FEGAFOOT', 'Fédération Gabonaise de Football', 1962),
('NATION', 'FA', 'The Football Association', 1863),
('NATION', 'SFA', 'Scottish Football Association', 1873),
('NATION', 'FAW', 'Football Association of Wales', 1876),
('NATION', 'IFA', 'Irish Football Association', 1880),
('NATION', 'GFF', 'Georgian Football Federation', 1990),
('NATION', 'GFA', 'Ghana Football Association', 1957),
('NATION', 'FGF', 'Fédération Guinéenne de Football', 1960),
('NATION', 'GFF', 'Gambia Football Federation', 1952),
('NATION', 'FFGB', 'Federação de Futebol da Guiné-Bissau', 1974),
('NATION', 'FEGUIFUT', 'Federación Ecuatoguineana de Fútbol', 1960),
('NATION', 'EPO', 'Hellenic Football Federation', 1926),
('NATION', 'GFA', 'Grenada Football Association', 1924),
('NATION', 'FENAFUTH', 'Federación Nacional de Fútbol de Guatemala', 1919),
('NATION', 'GFF', 'Guyana Football Federation', 1902),
('NATION', 'FENAFUTH', 'Federación Nacional Autónoma de Fútbol de Honduras', 1951),
('NATION', 'HNS', 'Hrvatski nogometni savez', 1912),
('NATION', 'FHF', 'Fédération Haïtienne de Football', 1904),
('NATION', 'MLSZ', 'Magyar Labdarúgó Szövetség', 1901),
('NATION', 'PSSI', 'Indonesian Football Association', 1930),
('NATION', 'AIFF', 'All India Football Federation', 1937),
('NATION', 'FAI', 'Football Association of Ireland', 1921),
('NATION', 'FFIRI', 'Football Federation Islamic Republic of Iran', 1920),
('NATION', 'IFA', 'Iraq Football Association', 1948),
('NATION', 'KSÍ', 'Knattspyrnusamband Íslands', 1947),
('NATION', 'IFA', 'Israel Football Association', 1928),
('NATION', 'FIGC', 'Federazione Italiana Giuoco Calcio', 1898),
('NATION', 'JFF', 'Jamaica Football Federation', 1910),
('NATION', 'JFA', 'Jordan Football Association', 1949),
('NATION', 'JFA', 'Japan Football Association', 1921),
('NATION', 'FFK', 'Football Federation of Kazakhstan', 1914),
('NATION', 'FKF', 'Football Kenya Federation', 1960),
('NATION', 'FFKR', 'Football Federation of the Kyrgyz Republic', 1992),
('NATION', 'FFC', 'Football Federation of Cambodia', 1933),
('NATION', 'KIFA', 'Kiribati Islands Football Association', 2005),
('NATION', 'SKNFA', 'Saint Kitts and Nevis Football Association', 1932),
('NATION', 'KFA', 'Korea Football Association', 1933),
('NATION', 'KFA', 'Kuwait Football Association', 1952),
('NATION', 'LFF', 'Lao Football Federation', 1951),
('NATION', 'LFA', 'Lebanese Football Association', 1933),
('NATION', 'LFA', 'Liberia Football Association', 1936),
('NATION', 'LFF', 'Libyan Football Federation', 1962),
('NATION', 'SLFA', 'Saint Lucia Football Association', 1979),
('NATION', 'LFV', 'Liechtensteiner Fussballverband', 1934),
('NATION', 'FFSL', 'Football Federation of Sri Lanka', 1939),
('NATION', 'LFA', 'Lesotho Football Association', 1932),
('NATION', 'LFF', 'Lithuanian Football Federation', 1922),
('NATION', 'FLF', 'Luxembourg Football Federation', 1908),
('NATION', 'LFF', 'Latvijas Futbola federācija', 1921),
('NATION', 'FRMF', 'Royal Moroccan Football Federation', 1956),
('NATION', 'FMF', 'Fédération Monegasque de Football', 1928),
('NATION', 'FMF', 'Federația Moldovenească de Fotbal', 1990),
('NATION', 'FMF', 'Fédération Malagasy de Football', 1961),
('NATION', 'FAM', 'Football Association of Maldives', 1982),
('NATION', 'FMF', 'Federación Mexicana de Fútbol Asociación', 1927),
('NATION', 'MISA', 'Marshall Islands Soccer Association', 1989),
('NATION', 'FFM', 'Football Federation of North Macedonia', 1922),
('NATION', 'FEMAFOOT', 'Fédération Malienne de Football', 1960),
('NATION', 'MFA', 'Malta Football Association', 1900),
('NATION', 'MFF', 'Myanmar Football Federation', 1947),
('NATION', 'FSCG', 'Fudbalski Savez Crne Gore', 2006),
('NATION', 'MFF', 'Mongolian Football Federation', 1959),
('NATION', 'FMF', 'Federação Moçambicana de Futebol', 1976),
('NATION', 'FFRIM', 'Fédération de Football de la République Islamique de Mauritanie', 1961),
('NATION', 'MFA', 'Mauritius Football Association', 1952),
('NATION', 'FAM', 'Football Association of Malawi', 1966),
('NATION', 'FAM', 'Football Association of Malaysia', 1933),
('NATION', 'NFA', 'Namibia Football Association', 1990),
('NATION', 'FENIFOOT', 'Fédération Nigerienne de Football', 1960),
('NATION', 'NFF', 'Nigeria Football Federation', 1945),
('NATION', 'FENIFUT', 'Federación Nicaragüense de Fútbol', 1931),
('NATION', 'NISA', 'Niue Island Soccer Association', 2012),
('NATION', 'KNVB', 'Koninklijke Nederlandse Voetbalbond', 1889),
('NATION', 'NFF', 'Norges Fotballforbund', 1902),
('NATION', 'ANFA', 'All Nepal Football Association', 1951),
('NATION', 'NFA', 'Nauru Football Association', 1974),
('NATION', 'NZF', 'New Zealand Football', 1891),
('NATION', 'OFA', 'Oman Football Association', 1978),
('NATION', 'PFF', 'Pakistan Football Federation', 1947),
('NATION', 'FEPAFUT', 'Federación Panameña de Fútbol', 1937),
('NATION', 'FPF', 'Federación Peruana de Futbol', 1922),
('NATION', 'PFF', 'Philippine Football Federation', 1907),
('NATION', 'PFA', 'Palau Football Association', 1990),
('NATION', 'PNGFA', 'Papua New Guinea Football Association', 1962),
('NATION', 'PZPN', 'Polski Związek Piłki Nożnej', 1919),
('NATION', 'FPF', 'Federación Puertorriqueña de Fútbol', 1940),
('NATION', 'DPRK FA', 'DPR Korea Football Association', 1945),
('NATION', 'FPF', 'Federação Portuguesa de Futebol', 1914),
('NATION', 'APF', 'Asociación Paraguaya de Fútbol', 1906),
('NATION', 'PFA', 'Palestine Football Association', 1928),
('NATION', 'QFA', 'Qatar Football Association', 1960),
('NATION', 'FRF', 'Federația Română de Fotbal', 1909),
('NATION', 'RFU', 'Russian Football Union', 1912),
('NATION', 'FERWAFA', 'Fédération Rwandaise de Football Association', 1972),
('NATION', 'SAFF', 'Saudi Arabian Football Federation', 1956),
('NATION', 'SFA', 'Sudan Football Association', 1936),
('NATION', 'FSF', 'Fédération Sénégalaise de Football', 1960),
('NATION', 'FAS', 'Football Association of Singapore', 1892),
('NATION', 'SIFF', 'Solomon Islands Football Federation', 1978),
('NATION', 'SLFA', 'Sierra Leone Football Association', 1967),
('NATION', 'FESFUT', 'Federación Salvadoreña de Fútbol', 1935),
('NATION', 'FSGC', 'Federazione Sammarinese Giuoco Calcio', 1931),
('NATION', 'SFF', 'Somali Football Federation', 1951),
('NATION', 'FSS', 'Football Association of Serbia', 1919),
('NATION', 'SSFA', 'South Sudan Football Association', 2011),
('NATION', 'FSF', 'Federação Santomense de Futebol', 1977),
('NATION', 'SVB', 'Surinaamse Voetbal Bond', 1920),
('NATION', 'SFZ', 'Slovenský futbalový zväz', 1938),
('NATION', 'NZS', 'Nogometna zveza Slovenije', 1920),
('NATION', 'SvFF', 'Svenska Fotbollförbundet', 1904),
('NATION', 'EFA', 'Eswatini Football Association', 1968),
('NATION', 'SFF', 'Seychelles Football Federation', 1988),
('NATION', 'SAFA', 'Syrian Arab Football Association', 1936),
('NATION', 'FTFA', 'Fédération Tchadienne de Football', 1962),
('NATION', 'FTF', 'Fédération Togolaise de Football', 1960),
('NATION', 'FAT', 'Football Association of Thailand', 1916),
('NATION', 'TFF', 'Tajikistan Football Federation', 1936),
('NATION', 'FFT', 'Football Federation of Turkmenistan', 1992),
('NATION', 'FFTL', 'Federação de Futebol de Timor-Leste', 2002),
('NATION', 'TFA', 'Tonga Football Association', 1965),
('NATION', 'TTFA', 'Trinidad and Tobago Football Association', 1908),
('NATION', 'FTF', 'Fédération Tunisienne de Football', 1957),
('NATION', 'TFF', 'Türkiye Futbol Federasyonu', 1923),
('NATION', 'CTFA', 'Chinese Taipei Football Association', 1924),
('NATION', 'TFF', 'Tanzania Football Federation', 1930),
('NATION', 'FUFA', 'Federation of Uganda Football Associations', 1924),
('NATION', 'UAF', 'Ukrainian Association of Football', 1991),
('NATION', 'AUF', 'Asociación Uruguaya de Fútbol', 1900),
('NATION', 'USSF', 'United States Soccer Federation', 1913),
('NATION', 'UFA', 'Uzbekistan Football Association', 1946),
('NATION', 'SVGFF', 'Saint Vincent and the Grenadines Football Federation', 1979),
('NATION', 'FVF', 'Federación Venezolana de Fútbol', 1926),
('NATION', 'VFF', 'Vietnam Football Federation', 1962),
('NATION', 'VFF', 'Vanuatu Football Federation', 1934),
('NATION', 'FFS', 'Football Federation Samoa', 1968),
('NATION', 'FFK', 'Football Federation of Kosovo', 1946),
('NATION', 'YFA', 'Yemen Football Association', 1962),
('NATION', 'SAFA', 'South African Football Association', 1991),
('NATION', 'FAZ', 'Football Association of Zambia', 1929),
('NATION', 'ZIFA', 'Zimbabwe Football Association', 1965);
--------------------------------------------------------------------------------
