/******************************************************************************* 
 * PROJECT NAME : FOOTBALL PLAYER DATABASE                                    
 *                                                                            
 * UNIVERSITY   : FEDERICO II - NAPOLI - ITALY                                 
 * FIELD        : COMPUTER SCIENCE                                            
 * CLASS        : DATA BASES I                                                
 * TEACHER      : SILVIO BARRA                                                
 * YEAR         : 2023-2024                                                   
 ******************************************************************************/


/*******************************************************************************
 * INSERT COUNTRY
 ******************************************************************************/


/*******************************************************************************
 * INSERT WORLD TYPE COUNTRY
 ******************************************************************************/
INSERT INTO country (type, code, name, year)
VALUES
('WORLD', 'WLD', 'World', 0);
--------------------------------------------------------------------------------


/*******************************************************************************
 * INSERT CONTINENT TYPE COUNTRY
 ******************************************************************************/
INSERT INTO country (type, code, name, year)
VALUES
('CONTINENT', 'AFR', 'Africa', 0),
('CONTINENT', 'ASI', 'Asia', 0),
('CONTINENT', 'ATA', 'Antartica', 0),
('CONTINENT', 'EUR', 'Europe', 0),
('CONTINENT', 'NCA', 'North Center America', 0),
('CONTINENT', 'OCN', 'Oceania', 0),
('CONTINENT', 'STA', 'South America', 0);
--------------------------------------------------------------------------------


/*******************************************************************************
 * INSERT NATION TYPE COUNTRY
 ******************************************************************************/
INSERT INTO country (type, code, name, year)
VALUES
('NATION', 'AFG', 'Afghanistan', 1919),
('NATION', 'AGO', 'Angola', 1975),
('NATION', 'ALB', 'Albania', 1912),
('NATION', 'AND', 'Andorra', 1278),
('NATION', 'ARE', 'United Arab Emirates', 1971),
('NATION', 'ARG', 'Argentina', 1816),
('NATION', 'ARM', 'Armenia', 1991),
('NATION', 'ATG', 'Antigua and Barbuda', 1981),
('NATION', 'AUS', 'Australia', 1901),
('NATION', 'AUT', 'Austria', 1955),
('NATION', 'AZE', 'Azerbaijan', 1991),
('NATION', 'BDI', 'Burundi', 1962),
('NATION', 'BEL', 'Belgium', 1830),
('NATION', 'BEN', 'Benin', 1960),
('NATION', 'BFA', 'Burkina Faso', 1960),
('NATION', 'BGD', 'Bangladesh', 1971),
('NATION', 'BGR', 'Bulgaria', 1908),
('NATION', 'BHR', 'Bahrain', 1971),
('NATION', 'BHS', 'Bahamas', 1973),
('NATION', 'BIH', 'Bosnia and Herzegovina', 1992),
('NATION', 'BLR', 'Belarus', 1991),
('NATION', 'BLZ', 'Belize', 1981),
('NATION', 'BOL', 'Bolivia', 1825),
('NATION', 'BRA', 'Brazil', 1822),
('NATION', 'BRB', 'Barbados', 1966),
('NATION', 'BRN', 'Brunei', 1984),
('NATION', 'BTN', 'Bhutan', 1949),
('NATION', 'BWA', 'Botswana', 1966),
('NATION', 'CAF', 'Central African Republic', 1960),
('NATION', 'CAN', 'Canada', 1867),
('NATION', 'CHE', 'Switzerland', 1291),
('NATION', 'CHL', 'Chile', 1818),
('NATION', 'CHN', 'China', 1949),
('NATION', 'CIV', 'Côte d''Ivoire', 1960),
('NATION', 'CMR', 'Cameroon', 1960),
('NATION', 'COD', 'Democratic Republic of the Congo', 1960),
('NATION', 'COG', 'Congo', 1960),
('NATION', 'COL', 'Colombia', 1810),
('NATION', 'COM', 'Comoros', 1975),
('NATION', 'CPV', 'Cabo Verde', 1975),
('NATION', 'CRI', 'Costa Rica', 1821),
('NATION', 'CUB', 'Cuba', 1902),
('NATION', 'CUW', 'Curaçao', 1954),
('NATION', 'CYP', 'Cyprus', 1960),
('NATION', 'CZE', 'Czech Republic', 1993),
('NATION', 'DEU', 'Germany', 1949),
('NATION', 'DJI', 'Djibouti', 1977),
('NATION', 'DMA', 'Dominica', 1978),
('NATION', 'DNK', 'Denmark', 980 ),
('NATION', 'DOM', 'Dominican Republic', 1844),
('NATION', 'DZA', 'Algeria', 1962),
('NATION', 'ECU', 'Ecuador', 1809),
('NATION', 'EGY', 'Egypt', 1952),
('NATION', 'ENG', 'England', 1707),
('NATION', 'ERI', 'Eritrea', 1991),
('NATION', 'ESP', 'Spain', 1492),
('NATION', 'EST', 'Estonia', 1918),
('NATION', 'ETH', 'Ethiopia', 1987),
('NATION', 'FIN', 'Finland', 1917),
('NATION', 'FJI', 'Fiji', 1970),
('NATION', 'FRA', 'France', 843 ),
('NATION', 'FSM', 'Micronesia', 1979),
('NATION', 'GAB', 'Gabon', 1960),
('NATION', 'GBR', 'United Kingdom', 1707),
('NATION', 'GEO', 'Georgia', 1991),
('NATION', 'GHA', 'Ghana', 1957),
('NATION', 'GIN', 'Guinea', 1958),
('NATION', 'GMB', 'Gambia', 1965),
('NATION', 'GNB', 'Guinea-Bissau', 1973),
('NATION', 'GNQ', 'Equatorial Guinea', 1968),
('NATION', 'GRC', 'Greece', 1821),
('NATION', 'GRD', 'Grenada', 1974),
('NATION', 'GTM', 'Guatemala', 1821),
('NATION', 'GUY', 'Guyana', 1966),
('NATION', 'HND', 'Honduras', 1821),
('NATION', 'HRV', 'Croatia', 1991),
('NATION', 'HTI', 'Haiti', 1804),
('NATION', 'HUN', 'Hungary', 1000),
('NATION', 'IDN', 'Indonesia', 1945),
('NATION', 'IND', 'India', 1947),
('NATION', 'IRL', 'Ireland', 1922),
('NATION', 'IRN', 'Iran', 1979),
('NATION', 'IRQ', 'Iraq', 1932),
('NATION', 'ISL', 'Iceland', 930 ),
('NATION', 'ISR', 'Israel', 1948),
('NATION', 'ITA', 'Italy', 1861),
('NATION', 'JAM', 'Jamaica', 1962),
('NATION', 'JOR', 'Jordan', 1946),
('NATION', 'JPN', 'Japan', 1890),
('NATION', 'KAZ', 'Kazakhstan', 1991),
('NATION', 'KEN', 'Kenya', 1963),
('NATION', 'KGZ', 'Kyrgyzstan', 1991),
('NATION', 'KHM', 'Cambodia', 1953),
('NATION', 'KIR', 'Kiribati', 1979),
('NATION', 'KNA', 'Saint Kitts and Nevis', 1983),
('NATION', 'KOR', 'South Korea', 1948),
('NATION', 'KWT', 'Kuwait', 1961),
('NATION', 'LAO', 'Lao People''s Democratic Republic', 1975),
('NATION', 'LBN', 'Lebanon', 1943),
('NATION', 'LBR', 'Liberia', 1847),
('NATION', 'LBY', 'Libya', 1951),
('NATION', 'LCA', 'Saint Lucia', 1979),
('NATION', 'LIE', 'Liechtenstein', 1719),
('NATION', 'LKA', 'Sri Lanka', 1948),
('NATION', 'LSO', 'Lesotho', 1966),
('NATION', 'LTU', 'Lithuania', 1009),
('NATION', 'LUX', 'Luxembourg', 963 ),
('NATION', 'LVA', 'Latvia', 1918),
('NATION', 'MAR', 'Morocco', 1956),
('NATION', 'MCO', 'Monaco', 1297),
('NATION', 'MDA', 'Moldova', 1991),
('NATION', 'MDG', 'Madagascar', 1960),
('NATION', 'MDV', 'Maldives', 1965),
('NATION', 'MEX', 'Mexico', 1810),
('NATION', 'MHL', 'Marshall Islands', 1986),
('NATION', 'MKD', 'North Macedonia', 1991),
('NATION', 'MLI', 'Mali', 1960),
('NATION', 'MLT', 'Malta', 1964),
('NATION', 'MMR', 'Myanmar', 1948),
('NATION', 'MNE', 'Montenegro', 2006),
('NATION', 'MNG', 'Mongolia', 1206),
('NATION', 'MOZ', 'Mozambique', 1975),
('NATION', 'MRT', 'Mauritania', 1960),
('NATION', 'MUS', 'Mauritius', 1968),
('NATION', 'MWI', 'Malawi', 1964),
('NATION', 'MYS', 'Malaysia', 1957),
('NATION', 'NAM', 'Namibia', 1990),
('NATION', 'NER', 'Niger', 1960),
('NATION', 'NGA', 'Nigeria', 1960),
('NATION', 'NIC', 'Nicaragua', 1821),
('NATION', 'NIR', 'Northern Ireland', 1921),
('NATION', 'NIU', 'Niue', 1994),	
('NATION', 'NLD', 'Netherlands', 1581),
('NATION', 'NOR', 'Norway', 1905),
('NATION', 'NPL', 'Nepal', 1768),
('NATION', 'NRU', 'Nauru', 1968),
('NATION', 'NZL', 'New Zealand', 1907),
('NATION', 'OMN', 'Oman', 1970),
('NATION', 'PAK', 'Pakistan', 1947),
('NATION', 'PAN', 'Panama', 1903),
('NATION', 'PER', 'Peru', 1821),
('NATION', 'PHL', 'Philippines', 1898),
('NATION', 'PLW', 'Palau', 1947),
('NATION', 'PNG', 'Papua New Guinea', 1975),
('NATION', 'POL', 'Poland', 966 ),
('NATION', 'PRI', 'Puerto Rico', 1898),
('NATION', 'PRK', 'North Korea', 1948),
('NATION', 'PRT', 'Portugal', 1143),
('NATION', 'PRY', 'Paraguay', 1811),
('NATION', 'PSE', 'Palestine', 1988),
('NATION', 'QAT', 'Qatar', 1971),
('NATION', 'ROU', 'Romania', 1859),
('NATION', 'RUS', 'Russian Federation', 1991),
('NATION', 'RWA', 'Rwanda', 1962),
('NATION', 'SAU', 'Saudi Arabia', 1932),
('NATION', 'SCT', 'Scotland', 1707),
('NATION', 'SDN', 'Sudan', 1956),
('NATION', 'SEN', 'Senegal', 1960),
('NATION', 'SGP', 'Singapore', 1965),
('NATION', 'SLB', 'Solomon Islands', 1978),
('NATION', 'SLE', 'Sierra Leone', 1961),
('NATION', 'SLV', 'El Salvador', 1821),
('NATION', 'SMR', 'San Marino', 301 ),
('NATION', 'SOM', 'Somalia', 1960),
('NATION', 'SRB', 'Serbia', 2006),
('NATION', 'SSD', 'South Sudan', 2011),
('NATION', 'STP', 'São Tomé and Príncipe', 1975),
('NATION', 'SUR', 'Suriname', 1975),
('NATION', 'SVK', 'Slovak Republic', 1993),
('NATION', 'SVN', 'Slovenia', 1991),
('NATION', 'SWE', 'Sweden', 1523),
('NATION', 'SWZ', 'Eswatini', 1968),
('NATION', 'SYC', 'Seychelles', 1976),
('NATION', 'SYR', 'Syria', 1946),
('NATION', 'TCD', 'Chad', 1960),
('NATION', 'TGO', 'Togo', 1960),
('NATION', 'THA', 'Thailand', 1238),
('NATION', 'TJK', 'Tajikistan', 1991),
('NATION', 'TKM', 'Turkmenistan', 1991),
('NATION', 'TLS', 'Timor-Leste', 2002),
('NATION', 'TON', 'Tonga', 1970),
('NATION', 'TTO', 'Trinidad and Tobago', 1962),
('NATION', 'TUN', 'Tunisia', 1956),
('NATION', 'TUR', 'Türkiye', 1923),
('NATION', 'TWN', 'Taiwan', 1911),
('NATION', 'TZA', 'Tanzania', 1964),
('NATION', 'UGA', 'Uganda', 1962),
('NATION', 'UKR', 'Ukraine', 1991),
('NATION', 'URY', 'Uruguay', 1828),
('NATION', 'USA', 'United States', 1776),
('NATION', 'UZB', 'Uzbekistan', 1991),
('NATION', 'VCT', 'Saint Vincent and the Grenadines', 1979),
('NATION', 'VEN', 'Venezuela', 1830),
('NATION', 'VNM', 'Vietnam', 1945),
('NATION', 'VUT', 'Vanuatu', 1980),
('NATION', 'WLS', 'Wales', 1967),
('NATION', 'WSM', 'Samoa', 1962),
('NATION', 'XKX', 'Kosovo', 2008),
('NATION', 'YEM', 'Yemen', 1918),
('NATION', 'ZAF', 'South Africa', 1910),
('NATION', 'ZMB', 'Zambia', 1964),
('NATION', 'ZWE', 'Zimbabwe', 1980);
--------------------------------------------------------------------------------


